### ISSUE TITLE
v0.9.24 Nexus 5x Android 7.1.1 Camera not working

### ISSUE THREAD

**Issue by ColRad** [inzhoop-co/LETH#10]
I get the following error when trying to use the camera. 
Reboot did not fix it. 
Awesome App by the way!

![screenshot_20161223-110157](https://cloud.githubusercontent.com/assets/3696742/21451507/dfc8cb4e-c8ff-11e6-8d7c-80a7eb16ea6c.png)

**Comment by hacktar** [comment]
Strange... maybe related to android 7.1.1 version.
We'll check, thanks

**Comment by milyInzhoop** [comment]
With this android version there is a known issue on cordova plugin.

**Comment by hacktar** [comment]
waiting for test on new release.
