### ISSUE TITLE
White screen

### ISSUE THREAD

**Issue by linagee** [inzhoop-co/LETH#23]
When I load the Android version on your page, I just get a white screen. What is the minimum version of Android required for this to run?

**Comment by hacktar** [comment]
We are sorry. Current version run with at least Android 6.0.1 but we are going to solve back compatibility asap

**Comment by milyInzhoop** [comment]
Could you be so kind to write us your android version?

**Comment by hacktar** [comment]
Now it works up version android 4.2.x.
Suggested version 5.x and up.

Go to test please.

Thanks
