### ISSUE TITLE
Add Ethereum Classic Support

### ISSUE THREAD

**Issue by ProphetDaniel** [inzhoop-co/LETH#27]
Transaction price in forked Ethereum kills some applications of the technology because of the current coin quotation. Ethereum Classic can be rather used to make sure smaller transactions are still viable. So adding it will greatly increse LETH user base.

**Comment by hacktar** [comment]
Do you have some public full node with API available like this:
--shh --rpcapi "web3,shh,eth"

let us know that we could make some test

**Comment by ProphetDaniel** [comment]
Try this https://www.myetherwallet.com/ and then select ETC node provided by Epool.io.

**Comment by ProphetDaniel** [comment]
I prepare this node today: [https://ethereum-classic.herokuapp.com/api](https://ethereum-classic.herokuapp.com/api). Let me know how it performs.

**Comment by hacktar** [comment]
What is the best way to identify the blockchain classic mainnet?

**Comment by ProphetDaniel** [comment]
You can issue the following command:
```
curl -X POST --data '{"jsonrpc":"2.0","method":"eth_getBlockByNumber","params":["0x1d4c00", true],"id":1}' https://ethereum-classic.herokuapp.com/api
```
So that you will be able to compare with the same block for forked Ethereum network. There should have a better way to identify though.

Because the node is still synchronizing with the network, that will return a null block. It will start working after the node synchronization has accounted for the DAO hard fork block number.
You can check synchronization by:
```
curl -X POST --data '{"jsonrpc":"2.0","method":"eth_blockNumber","params":[],"id":1}' https://ethereum-classic.herokuapp.com/api
```

**Comment by ChuckSRQ** [comment]
@hacktar The epool api is the same used by MyEtherWallet. You can always contact @etherninja for that.

**Comment by ProphetDaniel** [comment]
@ChuckSRQ for LETH the API endpoint needs to have whisper protocol enabled by default. As far as I know neither myEtherWallet nor epool have whisper enabled right now. It would be cool to see both activating it though.

**Comment by etherninja** [comment]
Hosting geth nodes require substantially more resources than parity. There is currently no plans to deploy geth for mewapi as a free service.

**Comment by hacktar** [comment]
we will wait for sync on https://ethereum-classic.herokuapp.com/api node.
You could just add this host on Settings of LETH and use chat over whisper but to manage asset we have to make some changes to network identification and wait for last block sync.

**Comment by ProphetDaniel** [comment]
@hacktar, if you compare [Ethereum Classic block #1,920,000](http://gastracker.io/block/1920000) with [Forked Ethereum block #1,920,000](https://etherscan.io/block/1920000) you will notice that both have the same parent hash but different hashes because that is the block in which Ethereum foundation executed the fork. This means you can identify Ethereum Classic network with the hash of the block #1,920,000:

- 0x4985f5ca3d2afbec36529aa96f74de3cc10a2a4a6c44f2157a57d2c6059a11bb for forked Ethereum
- 0x94365e3a8c0b35089c1d1195081fe7489b528a84b22199c916180db8b28ade7f for Ethereum Classic

**Comment by tcz001** [comment]
just in case, we should also consider using the chainId API which is more explicit for ETC and other forked chains, here is the [EIP](https://github.com/ethereum/EIPs/pull/695) we are proposing

**Comment by hacktar** [comment]
Done. Please use a synced host node with API for whisper messages

**Comment by kolya182** [comment]
A few more if needed:
https://web3.gastracker.io/  
https://etcrpc.viperid.online/
