### ISSUE TITLE
passwords do not match although only 1 field to enter password

### ISSUE THREAD

**Issue by der-blaue-elefant** [inzhoop-co/LETH#32]
When creating a wallet the app asks for a password and PIN. My password meets the requirements but the app shows an error message stating the passwords don't match.

There is only one input field for the password. How can they not match?

**Comment by der-blaue-elefant** [comment]
Android 6.01

**Comment by der-blaue-elefant** [comment]
![screenshot_2017-09-06-22-19-06-178_com inzhoop leth](https://user-images.githubusercontent.com/25263039/30132869-3161855a-9352-11e7-9dfb-786530225d72.png)

**Comment by hacktar** [comment]
Password and confirm (password).
First and second field are for the password .
Then put the pin code on third field.

**Comment by hacktar** [comment]
Please don't use this address because your 12 words seed now is public.

**Comment by der-blaue-elefant** [comment]
OK, could you just add something like a small but visible horizontal line to separate the inputs for password and the 4 digit code.
No worries, won't use this wallet!

**Comment by der-blaue-elefant** [comment]
Could you please indicate, that the PIN is optional? How should the user know?
