### ISSUE TITLE
loading progress bar

### ISSUE THREAD

**Issue by der-blaue-elefant** [inzhoop-co/LETH#34]
After the initial password input, the loading takes forever (ok, nearly, at least a few minutes, not finished yet). Please add a progress bar to show the user what's happening or if the app is stuck at some point.

**Comment by der-blaue-elefant** [comment]
After killing and restarting it shows a connection error. "Can't connect to ...*

**Comment by der-blaue-elefant** [comment]
Seems to be a more general problem. When ever it's loading and nothing happens for a while, I kill and restart it. Then it shows a "Oops something went wrong, connection error" message.

**Comment by hacktar** [comment]
please check your internet connection.
