### ISSUE TITLE
can't abort loading 

### ISSUE THREAD

**Issue by der-blaue-elefant** [inzhoop-co/LETH#35]
When I try to abort the "loading" process by hitting the built in back button of my phone, nothing happens. I would expect it to go "where it came from" = last screen without loading.
Problem is related to "back button doesn't work" in #33 and "loading takes forever" in #34.

**Comment by hacktar** [comment]
as suggested for #34 check internet connection

**Comment by hacktar** [comment]
if you abort loading, you cannot create a wallet and then it doesn't work.
