### ISSUE TITLE
sent messages in chat don't show up

### ISSUE THREAD

**Issue by der-blaue-elefant** [inzhoop-co/LETH#36]
1. type a message in the chat tab
2. click blue arrow next to the keyboard to send it
3. message doesn't show up in chat protocoll

Maybe this is related to connection errors but I would expect the message to be shown anyway, also if it hasn't been successfully sent yet.

**Comment by der-blaue-elefant** [comment]
![screenshot_2017-09-06-23-06-23-528_com inzhoop leth](https://user-images.githubusercontent.com/25263039/30134635-15dbf634-9358-11e7-80d5-411ea7f79e42.png)

**Comment by hacktar** [comment]
related to connection error, you wasn't able to create the wallet and keys identity.
