### ISSUE TITLE
share address with friend -- where to proceed?

### ISSUE THREAD

**Issue by der-blaue-elefant** [inzhoop-co/LETH#37]
When sharing an ether address I can choose email, SMS (both working) or chat. Once I chose a friend to share the address with, I can't proceed in any way. Maybe this is related to connection problems.

**Comment by der-blaue-elefant** [comment]
![screenshot_2017-09-06-23-09-38-281_com inzhoop leth](https://user-images.githubusercontent.com/25263039/30134834-d39df546-9358-11e7-8652-e3403de0ac39.png)

**Comment by hacktar** [comment]
I don't see any new user added in chat, so i suppose that all your error are related to the fact that you never created a wallet (maybe for missing connection or for aborting the app during loading ).
Please check if you have an address from related tab.
