### ISSUE TITLE
enable PIN by default

### ISSUE THREAD

**Issue by der-blaue-elefant** [inzhoop-co/LETH#38]
I entered a PIN when creating a wallet (see #32). Why isn't it activated by default?

**Comment by der-blaue-elefant** [comment]
![screenshot_2017-09-06-23-14-31-497_com inzhoop leth](https://user-images.githubusercontent.com/25263039/30134919-3041617a-9359-11e7-88f7-b381acb723dc.png)

**Comment by hacktar** [comment]
because the use of PIN is optional.

**Comment by der-blaue-elefant** [comment]
So please indicate, that it's optional! The user cannot see it in the GUI. I guess it's not a big problem to enable the PIN if it was provided during the wallet creation process and to disable it if it wasn't entered.
