### ISSUE TITLE
localisations - German

### ISSUE THREAD

**Issue by ScenicSwisscoast** [inzhoop-co/LETH#42]
We would be happy to translate a localisation in German for use in D-A-CH Germany/Austria/Switzerland.
Menu-Strings are most important maybe something like that would increas usability in DACH

Here are the important translations (in the menu at the bottom of the app)

Store-Store
Chat-Chat
Friends-Freunde
Wallet-Brieftasche
Address-Adresse
Settings-Einstellungen

Custom token - zusätzlicher Token
Add a custom Token - zusätzlicher Token hinzufügen

and here are the low priority translations in the Menu - Settings - Einstellungen

Host type - host typ
host - host
Backup - Backup
Backup your Wallet - Backup Brieftasche
Restore a Wallet - eine Brieftasche wiederherstellen
PIN - PIN
Enable - aktivieren
Activity - Aktivität
Background mode - Hintergrundsmodus
Vibrate notification - Vibrationsbenachrichtigung
Communication - Kommunikation
NFC sensor - NFC Sensor
Geolocation - Geolokalisation
Exchange - Börse
Base currency - Basiswährung

**Comment by hacktar** [comment]
Well done, task in progress

**Comment by uNki23** [comment]
I would translate it like:

{
  "STORE_TAB": "Store",
  "CHAT_TAB": "Chat",
  "FRIENDS_TAB": "Freunde",
  "WALLET_TAB": "Brieftasche",
  "ADDRESS_TAB": "Adresse",
  "SETTINGS_TAB": "Einstellungen",
  "LANGUAGES_TITLE": "Sprachen",
  "CHOOSE_LANGUAGE": "Sprache wählen",
  "CUSTOM_TOKEN": "Individueller Token",
  "ADD_CUSTOM_TOKEN": "Individuellen Token hinzufügen",
  "ADDRESS_TITLE":"Adresse",
  "BLACKLIST_TITLE":"Sperrliste",
  "CHATS_TITLE":"Chats",
  "FRIENDS_TITLE": "Freunde",
  "HOST_NODES_TITLE":"Hosts",
  "TRANSACTIONS_TITLE":"Transaktionen",
  "WALLET_TITLE":"Brieftasche",
  "SETTINGS_TITLE":"Einstellungen",
  "HOST_PROVIDER_ADDRESS": "Host Anbieter Adresse", //or only "Host Adresse"
  "HOST_TYPE": "Host Typ",
  "HOST": "Host",
  "BACKUP": "Backup",
  "BACKUP_WALLET": "Backup Brieftasche",
  "RESTORE_WALLET": "Brieftasche wiederherstellen",
  "PIN": "Pin",
  "PIN_ENABLE": "Pin aktivieren",
  "TOUCHID": "TouchID",
  "BANNED_USERS": "Gesperrte Benutzer",
  "MANAGE_BLACKLIST": "Sperrliste verwalten",
  "LANGUAGES":"Sprachen",
  "SET_LANGUAGES":"Sprache wählen",
  "ACTIVITY": "Aktivität",
  "BACKGROUND_MODE": "Hintergrundmodus",
  "VIBRATE_NOTIFICATION": "Vibrationsbenachrichtigung",
  "COMMUNICATION": "Kommunikation",
  "NFC_SENSOR": "NFC Sensor",
  "GEOLOCATION": "Standort",
  "EXCHANGE":"Börse",
  "BASE_CURRENCY":"Basiswährung"
}

**Comment by hacktar** [comment]
Thanks, we will integrate with current translation

**Comment by hacktar** [comment]
missing some few translations, but now you can choose your language.
