### ISSUE TITLE
Cannot change host setting

### ISSUE THREAD

**Issue by grishick** [inzhoop-co/LETH#47]
This is in Advanced Settings in the mobile app on iOS. Typing in new host name or tapping the second pre-filled URL does not have any effect.

**Comment by hacktar** [comment]
Can you test this feature after restart the app?
Please let me know,
Thanks

**Comment by grishick** [comment]
@hacktar it worked after restart and also I immediately saw new tokens in the Store after switching to port 8545. Pardon my noob question, since I am still wrapping my head around the lightwallet and web3. What are those URLs for?

**Comment by hacktar** [comment]
Lightwallet works in connection with a geth full node with some enabled API and services like shh.
The host nodes preconfigured are for connect to testnet (Ropsten) and Mainnet. Also, you can use your own custom node.

**Comment by grishick** [comment]
thanks!

**Comment by hacktar** [comment]
great!
