### ISSUE TITLE
LETH 0.9.23 transaction display and address fetching

### ISSUE THREAD

**Issue by jdetychey** [inzhoop-co/LETH#5]
Hi,

clicking on the bust shape lead to the friendlist address but sometimes after selecting the address it doens t show in the address field after. This issue is solved when rebooting the app.
also the transaction list is not displayed.

[http://pasteboard.co/bJo2JJtgX.png](http://pasteboard.co/bJo2JJtgX.png)

app: 0.9.23
phone: samsung s6

**Comment by hacktar** [comment]
The problem is reproducible from second bust shape selection.
Refactoring for the modal friend choose is needed ...
WIP

**Comment by hacktar** [comment]
fixed on new version
