### ISSUE TITLE
Constant functions return empty results in LETH when they work with MetaMask

### ISSUE THREAD

**Issue by grishick** [inzhoop-co/LETH#56]
My Solidity contract has the following function

```
    function getFriend(address _friend) public view returns (bytes32 friendName) {
        require(_friend != address(0));
        return addressBook[msg.sender][_friend];
    }
```
In my LETH DApp I have a call to this function that looks like this:

```
dappContract.getFriend(addr, function(error, friendName) {
                if(error) {
                    console.log("Error in getFriend: ", error)
                    if(cb) {
                        cb(error, null);
                    }
                } else {
                    console.log("Received friend name in hex", friendName);
                }
            });
```

calling this code, results in the following network trace in Chrome Developer console:

Request:
`{"jsonrpc":"2.0","id":269,"method":"eth_call","params":[{"to":"0xd2c92e41106ae0cc0e573d19ed739b433bcc33ae","data":"0x30ead4690000000000000000000000006a0c0b023cafd4a1f7b6f16575329b7ac0d59fcc"},"latest"]}`

Response:
`{"jsonrpc":"2.0","id":269,"result":"0x0000000000000000000000000000000000000000000000000000000000000000"}`

The response is incorrect, because "addressBook" contains the element that should be returned. In this case, the element's value is "0x4163633300000000000000000000000000000000000000000000000000000000".

When I enable MetaMask extension, unlock the wallet in MetaMask and reload LETH web app, MetaMask injects its own web3 provider instead of LETH's. With MetaMask's web3 provider the same call works correctly:

Request:

`{"jsonrpc":"2.0","id":38,"method":"eth_call","params":[{"to":"0xd2c92e41106ae0cc0e573d19ed739b433bcc33ae","data":"0x30ead4690000000000000000000000006a0c0b023cafd4a1f7b6f16575329b7ac0d59fcc","from":"0x9451def8ca3662d40b5569dc9181383789515748"},"latest"]`

Response:
`{"jsonrpc":"2.0","id":38,"result":"0x4163633300000000000000000000000000000000000000000000000000000000"}`

**Comment by grishick** [comment]
There seems to be a simple workaround:

`dappContract.getFriend(addr, {'from':$service.address()}, function(error, friendName) {`

but in any case, this seems like a bug, because this same code works fine with MetaMask, in Toshi and in Status.

**Comment by hacktar** [comment]
maybe could be due to different web3 version used, i will check
