### ISSUE TITLE
User interface message chat board copying

### ISSUE THREAD

**Issue by jdetychey** [inzhoop-co/LETH#6]
Long clicking on a message doesn t display a menu to copy/share the message
Also when selecting the field to write, the keyboard pops up as usual but don't push the chat field to the last message. Therefore when the user write he has to push the conversation up to see the last message

**Comment by hacktar** [comment]
It is true! Now long click on message gives access to some contextual action.

i.e.:
- Hold on position shared message open maps with that position
- Hold on shared contact message add to address book
-  and so on...

But for sure we need to introduce copy text feature.

**Comment by jdetychey** [comment]
Also there should be a way to store logs somehow inside the phone memory. 
For example I received a msg from an unknown user saying "this app is so cool" I closed the app before answering and it's lost forever :cry:

**Comment by hacktar** [comment]
Copy and cool other features added in action sheet menu: just hold on messages to test them.
