### ISSUE TITLE
Failure to display number of token owned

### ISSUE THREAD

**Issue by jdetychey** [inzhoop-co/LETH#7]
After adding a custom Token in the store section, going to the Wallet section and choosing the token in " coin to pay with", when selecting the custom token the number displayed is wrong. It is the number of Ether at the address instead.
Sending the token works properly

**Comment by hacktar** [comment]
Can't reproduce!
How many type of coin you have in store?
Could you use option "Share" of Custom Token with user Inzhoop to test it?

**Comment by jdetychey** [comment]
I have only one custom token  (i used the erc20 compliant contract from open zeppelin )

**Comment by hacktar** [comment]
Are you able to select coin Inzhoop (community coin) preinstalled?

**Comment by jdetychey** [comment]
Yep 
It displays properly my amount of community coins: 0
0xdf78a90e9b8ac9cde99597b0b60eccbb3fcebeec

**Comment by hacktar** [comment]
Could you use option "Share" of Custom Token with user Inzhoop to test it?

**Comment by jdetychey** [comment]
Sure, where is the option "share"?
in the store section I see my own token and inzhoop. I have no available option but to add another one. Long clicking on inzhoop or my token don t do anything.

**Comment by hacktar** [comment]
Try swipe on the left upon the token added and you'll se options (share, unset, delete)

**Comment by hacktar** [comment]
Great! I can reproduce now.
Are you sure it is a ERC20 standard? Maybe we have a problem because assume that a token have always decimals() function.

We try to fix for better.

Great report, thanks a lot.

**Comment by hacktar** [comment]
Try delete and add again your custom token.
Now you have to provide decimals positions.
Let us know
