### ISSUE TITLE
There is no way to add an address as friend [enhancement]

### ISSUE THREAD

**Issue by jdetychey** [inzhoop-co/LETH#8]
Am I missing something ?
It seems like you can not add address to your friend list

**Comment by hacktar** [comment]
There is many different ways to add a friend but first we need to explain user definition for LETH.
A user (and than a friend) on LETH is identified from 2 addresses :
- wallet address
- shh identity address

So, you can add a friend (with his adresses) in several ways:
- Hold on any message in pubblic chat of specific user to add
- Hold on share contact from chat
- Scan QR Address with LETH
- Click on shared Address received via SMS, EMAIL or CHAT

You could NOT add a friend manually.

**Comment by hacktar** [comment]
Now with a better user experience.
